<?php

use Illuminate\Database\Seeder;

class MemberTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('members')->delete();

        $m = App\Member::create(['first_name' => 'Αθανάσιος', 'last_name' => ' Αθανασίου (Νάσος)', 'order'=> 1, 'district_id' => 8]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Χαράλαμπος', 'last_name' => ' Αθανασίου', 'order'=> 1, 'district_id' => 39]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Ακριώτης', 'order'=> 1, 'district_id' => 19]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Αμανατίδης', 'order'=> 1, 'district_id' => 2]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ευαγγελία', 'last_name' => ' Αμμανατίδου-Πασχαλίδου (Λίτσα)(fr)', 'order'=> 1, 'district_id' => 11]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Αμυράς', 'order'=> 1, 'district_id' => 10]);
        $m->groups()->attach([6]);
        $m = App\Member::create(['first_name' => 'Αθανασία', 'last_name' => ' Αναγνωστοπούλου (Σία)', 'order'=> 1, 'district_id' => 9]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Σάββας', 'last_name' => ' Αναστασιάδης', 'order'=> 2, 'district_id' => 11]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Ανδριανός', 'order'=> 1, 'district_id' => 5]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Σταυρούλα', 'last_name' => ' Αντωνάκου', 'order'=> 1, 'district_id' => 3]);
        $m->groups()->attach([6]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Αντωνιάδης', 'order'=> 1, 'district_id' => 53]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Μαρία', 'last_name' => ' Αντωνίου', 'order'=> 1, 'district_id' => 29]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Ουρανία', 'last_name' => ' Αντωνοπούλου', 'order'=> 1, 'district_id' => 18]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ευάγγελος', 'last_name' => ' Αποστόλου', 'order'=> 2, 'district_id' => 19]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Φωτεινή', 'last_name' => ' Αραμπατζή', 'order'=> 1, 'district_id' => 50]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Σταύρος', 'last_name' => ' Αραχωβίτης', 'order'=> 1, 'district_id' => 36]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Μιχαήλ', 'last_name' => ' Αρβανίτης', 'order'=> 2, 'district_id' => 9]);
        $m->groups()->attach([7]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Αρβανιτίδης', 'order'=> 3, 'district_id' => 11]);
        $m->groups()->attach([4]);
        $m = App\Member::create(['first_name' => 'Άννα-Μισέλ', 'last_name' => ' Ασημακοπούλου', 'order'=> 2, 'district_id' => 10]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Ελευθέριος', 'last_name' => ' Αυγενάκης', 'order'=> 1, 'district_id' => 24]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Ελένη', 'last_name' => ' Αυλωνίτου', 'order'=> 3, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Άννα', 'last_name' => ' Βαγενά', 'order'=> 1, 'district_id' => 37]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ευαγγελία', 'last_name' => ' Βαγιωνάκη (Βάλια)', 'order'=> 1, 'district_id' => 56]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Βαγιωνάς', 'order'=> 1, 'district_id' => 55]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Φωτεινή', 'last_name' => ' Βάκη', 'order'=> 1, 'district_id' => 30]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Όλγα-Νάντια', 'last_name' => ' Βαλαβάνη', 'order'=> 4, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Μιλτιάδης', 'last_name' => ' Βαρβιτσιώτης', 'order'=> 5, 'district_id' => 10]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Σωκράτης', 'last_name' => ' Βαρδάκης', 'order'=> 2, 'district_id' => 24]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Αθανάσιος', 'last_name' => ' Βαρδαλής', 'order'=> 2, 'district_id' => 2]);
        $m->groups()->attach([2]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Βαρεμένος', 'order'=> 1, 'district_id' => 4]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Βαρουφάκης (Γιάνης)', 'order'=> 6, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ευάγγελος', 'last_name' => ' Βενιζέλος', 'order'=> 3, 'district_id' => 2]);
        $m->groups()->attach([4]);
        $m = App\Member::create(['first_name' => 'Απόστολος', 'last_name' => ' Βεσυρόπουλος', 'order'=> 1, 'district_id' => 23]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Δημήτριος', 'last_name' => ' Βέττας', 'order'=> 1, 'district_id' => 52]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Δημήτριος', 'last_name' => ' Βίτσας', 'order'=> 7, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Βλάσης', 'order'=> 1, 'district_id' => 6]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Θ. Βλάχος', 'order'=> 2, 'district_id' => 8]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Μαυρουδής', 'last_name' => ' Βορίδης (Μάκης)', 'order'=> 3, 'district_id' => 8]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Σοφία', 'last_name' => ' Βούλτεψη', 'order'=> 8, 'district_id' => 10]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Νικόλαος', 'last_name' => ' Βούτσης', 'order'=> 1, 'district_id' => 1]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Βρούτσης', 'order'=> 1, 'district_id' => 35]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Ιωάννα', 'last_name' => ' Γαϊτάνη', 'order'=> 4, 'district_id' => 2]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Δημήτριος', 'last_name' => ' Γάκης', 'order'=> 1, 'district_id' => 16]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Γαλέος', 'order'=> 2, 'district_id' => 5]);
        $m->groups()->attach([7]);
        $m = App\Member::create(['first_name' => 'Φώφη', 'last_name' => ' Γεννηματά', 'order'=> 9, 'district_id' => 10]);
        $m->groups()->attach([4]);
        $m = App\Member::create(['first_name' => 'Ελένη', 'last_name' => ' Γερασιμίδου', 'order'=> 4, 'district_id' => 11]);
        $m->groups()->attach([2]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Γερμενής', 'order'=> 10, 'district_id' => 10]);
        $m->groups()->attach([7]);
        $m = App\Member::create(['first_name' => 'Όλγα', 'last_name' => ' Γεροβασίλη', 'order'=> 1, 'district_id' => 7]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Γεωργαντάς', 'order'=> 1, 'district_id' => 32]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Σπυρίδων-Άδωνις', 'last_name' => ' Γεωργιάδης', 'order'=> 11, 'district_id' => 10]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Ευσταθία', 'last_name' => ' Γεωργοπούλου-Σαλτάρη (Έφη)', 'order'=> 1, 'district_id' => 22]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Γεράσιμος', 'last_name' => ' Γιακουμάτος', 'order'=> 12, 'district_id' => 10]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Στέργιος', 'last_name' => ' Γιαννάκης', 'order'=> 1, 'district_id' => 46]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Ευστάθιος', 'last_name' => ' Γιαννακίδης', 'order'=> 1, 'district_id' => 43]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Βασίλειος', 'last_name' => ' Γιόγιακας', 'order'=> 1, 'district_id' => 25]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Αναστασία', 'last_name' => ' Γκαρά (Νατάσα)', 'order'=> 1, 'district_id' => 17]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Στέφανος', 'last_name' => ' Γκίκας', 'order'=> 2, 'district_id' => 30]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Γκιόκας', 'order'=> 4, 'district_id' => 8]);
        $m->groups()->attach([2]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Γκιουλέκας', 'order'=> 5, 'district_id' => 2]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Φώτιος', 'last_name' => ' Γραικός', 'order'=> 5, 'district_id' => 11]);
        $m->groups()->attach([7]);
        $m = App\Member::create(['first_name' => 'Αντώνιος', 'last_name' => ' Γρέγος', 'order'=> 6, 'district_id' => 2]);
        $m->groups()->attach([7]);
        $m = App\Member::create(['first_name' => 'Λεωνίδας', 'last_name' => ' Γρηγοράκος', 'order'=> 2, 'district_id' => 36]);
        $m->groups()->attach([4]);
        $m = App\Member::create(['first_name' => 'Σταύρος', 'last_name' => ' Γρηγόρης', 'order'=> 1, 'district_id' => 40]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Αθανάσιος', 'last_name' => ' Δαβάκης', 'order'=> 3, 'district_id' => 36]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Σπυρίδων', 'last_name' => ' Δανέλλης', 'order'=> 3, 'district_id' => 24]);
        $m->groups()->attach([6]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Δέδες', 'order'=> 5, 'district_id' => 8]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Δελημήτρος', 'order'=> 1, 'district_id' => 41]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Νικόλαος-Γεώργιος', 'last_name' => ' Δένδιας', 'order'=> 13, 'district_id' => 10]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Δερμιτζάκης', 'order'=> 1, 'district_id' => 38]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Δημαράς', 'order'=> 14, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Χρίστος', 'last_name' => ' Δήμας', 'order'=> 1, 'district_id' => 34]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Δημήτριος', 'last_name' => ' Δημητριάδης', 'order'=> 1, 'district_id' => 33]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Αναστάσιος', 'last_name' => ' Δημοσχάκης (Τάσος)', 'order'=> 2, 'district_id' => 17]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Ευάγγελος', 'last_name' => ' Διαμαντόπουλος', 'order'=> 2, 'district_id' => 29]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ηρώ', 'last_name' => ' Διώτη', 'order'=> 2, 'district_id' => 37]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Δραγασάκης', 'order'=> 15, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Δριβελέγκας', 'order'=> 2, 'district_id' => 55]);
        $m->groups()->attach([4]);
        $m = App\Member::create(['first_name' => 'Θεόδωρος', 'last_name' => ' Δρίτσας', 'order'=> 2, 'district_id' => 3]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Παναγιώτα', 'last_name' => ' Δριτσέλη', 'order'=> 1, 'district_id' => 51]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Δημήτριος', 'last_name' => ' Εμμανουηλίδης', 'order'=> 1, 'district_id' => 27]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ζήσης', 'last_name' => ' Ζάννας', 'order'=> 1, 'district_id' => 45]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ελένη', 'last_name' => ' Ζαρούλια', 'order'=> 16, 'district_id' => 10]);
        $m->groups()->attach([7]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Ζαχαριάς', 'order'=> 2, 'district_id' => 6]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Χουσεϊν', 'last_name' => ' Ζεϊμπέκ', 'order'=> 2, 'district_id' => 43]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Ζερδελής', 'order'=> 2, 'district_id' => 39]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Ζουράρης', 'order'=> 7, 'district_id' => 2]);
        $m->groups()->attach([1]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος-Ηρακλής', 'last_name' => ' Ήσυχος', 'order'=> 17, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Μαρία', 'last_name' => ' Θελερίτη', 'order'=> 2, 'district_id' => 34]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Σταύρος', 'last_name' => ' Θεοδωράκης', 'order'=> 2, 'district_id' => 56]);
        $m->groups()->attach([6]);
        $m = App\Member::create(['first_name' => 'Αφροδίτη', 'last_name' => ' Θεοπεφτάτου', 'order'=> 1, 'district_id' => 31]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Θεοχάρης', 'last_name' => ' Θεοχάρης (Χάρης)', 'order'=> 18, 'district_id' => 10]);
        $m->groups()->attach([6]);
        $m = App\Member::create(['first_name' => 'Αικατερίνη', 'last_name' => ' Ιγγλέζη', 'order'=> 3, 'district_id' => 55]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ηλίας', 'last_name' => ' Ιωαννίδης', 'order'=> 2, 'district_id' => 27]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ιωαννέτα', 'last_name' => ' Καββαδία (Αννέτα)', 'order'=> 19, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Καΐσας', 'order'=> 3, 'district_id' => 17]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Νικήτας', 'last_name' => ' Κακλαμάνης', 'order'=> 2, 'district_id' => 1]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Σταύρος', 'last_name' => ' Καλαφάτης', 'order'=> 8, 'district_id' => 2]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Ηλίας', 'last_name' => ' Καματερός', 'order'=> 2, 'district_id' => 16]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Δημήτριος', 'last_name' => ' Καμμένος', 'order'=> 1, 'district_id' => 12]);
        $m->groups()->attach([1]);
        $m = App\Member::create(['first_name' => 'Παναγιώτης', 'last_name' => ' Καμμένος (Πάνος)', 'order'=> 20, 'district_id' => 10]);
        $m->groups()->attach([1]);
        $m = App\Member::create(['first_name' => 'Γαρυφαλλιά', 'last_name' => ' Κανέλλη (Λιάνα)', 'order'=> 3, 'district_id' => 1]);
        $m->groups()->attach([2]);
        $m = App\Member::create(['first_name' => 'Μαρία', 'last_name' => ' Κανελλοπούλου', 'order'=> 3, 'district_id' => 9]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Αϊχάν', 'last_name' => ' Καρά Γιουσούφ', 'order'=> 1, 'district_id' => 48]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Καραγιάννης', 'order'=> 1, 'district_id' => 26]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Χρήστος', 'last_name' => ' Καραγιαννίδης', 'order'=> 1, 'district_id' => 15]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Καραγκούνης', 'order'=> 2, 'district_id' => 4]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Νικόλαος', 'last_name' => ' Καραθανασόπουλος', 'order'=> 4, 'district_id' => 9]);
        $m->groups()->attach([2]);
        $m = App\Member::create(['first_name' => 'Ευαγγελία', 'last_name' => ' Καρακώστα (Εύη)', 'order'=> 2, 'district_id' => 12]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Άννα', 'last_name' => ' Καραμανλή', 'order'=> 21, 'district_id' => 10]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Κώστας', 'last_name' => ' Καραμανλής', 'order'=> 9, 'district_id' => 2]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Αχιλλέα Καραμανλής', 'order'=> 2, 'district_id' => 50]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Απόστολος', 'last_name' => ' Καραναστάσης', 'order'=> 2, 'district_id' => 52]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Θεόδωρος', 'last_name' => ' Καράογλου', 'order'=> 6, 'district_id' => 11]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Ευφροσύνη', 'last_name' => ' Καρασαρλίδου (Φρόσω)', 'order'=> 2, 'district_id' => 23]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Καρασμάνης', 'order'=> 1, 'district_id' => 44]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Παναγιώτης', 'last_name' => ' Καρκατσούλης', 'order'=> 2, 'district_id' => 18]);
        $m->groups()->attach([6]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Κασαπίδης', 'order'=> 2, 'district_id' => 33]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Ηλίας', 'last_name' => ' Κασιδιάρης', 'order'=> 6, 'district_id' => 8]);
        $m->groups()->attach([7]);
        $m = App\Member::create(['first_name' => 'Ειρήνη', 'last_name' => ' Κασιμάτη (Νίνα)', 'order'=> 3, 'district_id' => 12]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Χαρίσιος', 'last_name' => ' Κάτανας', 'order'=> 3, 'district_id' => 33]);
        $m->groups()->attach([1]);
        $m = App\Member::create(['first_name' => 'Βασιλική', 'last_name' => ' Κατριβάνου', 'order'=> 22, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Χρυσούλα', 'last_name' => ' Κατσαβριά-Σιωροπούλου', 'order'=> 1, 'district_id' => 28]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ανδρέας', 'last_name' => ' Κατσανιώτης', 'order'=> 5, 'district_id' => 9]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Κατσαφάδος', 'order'=> 3, 'district_id' => 3]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Μάριος', 'last_name' => ' Κάτσης', 'order'=> 2, 'district_id' => 25]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Χρήστος', 'last_name' => ' Κατσώτης', 'order'=> 23, 'district_id' => 10]);
        $m->groups()->attach([2]);
        $m = App\Member::create(['first_name' => 'Χαρούλα', 'last_name' => ' Καφαντάρη (Χαρά)', 'order'=> 24, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Βασίλειος', 'last_name' => ' Κεγκέρογλου', 'order'=> 4, 'district_id' => 24]);
        $m->groups()->attach([4]);
        $m = App\Member::create(['first_name' => 'Σίμος', 'last_name' => ' Β. Κεδίκογλου', 'order'=> 3, 'district_id' => 19]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Χρήστος', 'last_name' => ' Κέλλας', 'order'=> 3, 'district_id' => 37]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Νίκη', 'last_name' => ' Κεραμέως', 'order'=> 3, 'district_id' => 18]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Όλγα', 'last_name' => ' Κεφαλογιάννη', 'order'=> 4, 'district_id' => 1]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Αχ. Κεφαλογιάννης', 'order'=> 1, 'district_id' => 47]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Βασίλειος', 'last_name' => ' Κικίλιας', 'order'=> 5, 'district_id' => 1]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Δημήτριος', 'last_name' => ' Κοδέλας', 'order'=> 3, 'district_id' => 5]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Παναγιώτα', 'last_name' => ' Κοζομπόλη-Αμανατίδη', 'order'=> 1, 'district_id' => 42]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Βασίλειος', 'last_name' => ' Κόκκαλης', 'order'=> 4, 'district_id' => 37]);
        $m->groups()->attach([1]);
        $m = App\Member::create(['first_name' => 'Μαρία', 'last_name' => ' Κόλλια-Τσαρουχά', 'order'=> 3, 'district_id' => 50]);
        $m->groups()->attach([1]);
        $m = App\Member::create(['first_name' => 'Εμμανουήλ', 'last_name' => ' Κόνσολας (Μάνος)', 'order'=> 3, 'district_id' => 16]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Χαράλαμπος-Σταύρος', 'last_name' => ' Κοντονής', 'order'=> 1, 'district_id' => 21]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Αλέξανδρος', 'last_name' => ' Κοντός', 'order'=> 3, 'district_id' => 43]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Νικόλαος', 'last_name' => ' Κούζηλος', 'order'=> 4, 'district_id' => 3]);
        $m->groups()->attach([7]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Κουκοδήμος', 'order'=> 2, 'district_id' => 45]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Κουμουτσάκος', 'order'=> 25, 'district_id' => 10]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Έλενα', 'last_name' => ' Κουντουρά', 'order'=> 6, 'district_id' => 1]);
        $m->groups()->attach([1]);
        $m = App\Member::create(['first_name' => 'Αναστάσιος', 'last_name' => ' Κουράκης (Τάσος)', 'order'=> 10, 'district_id' => 2]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Θεοφάνης', 'last_name' => ' Κουρεμπές (Φάνης)', 'order'=> 3, 'district_id' => 34]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Παναγιώτης', 'last_name' => ' Κουρουμπλής', 'order'=> 26, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Γιάννης', 'last_name' => ' Κουτσούκος', 'order'=> 2, 'district_id' => 22]);
        $m->groups()->attach([4]);
        $m = App\Member::create(['first_name' => 'Δημήτριος', 'last_name' => ' Κουτσούμπας', 'order'=> 27, 'district_id' => 10]);
        $m->groups()->attach([2]);
        $m = App\Member::create(['first_name' => 'Τιμολέων', 'last_name' => ' Κοψαχείλης', 'order'=> 1, 'district_id' => 14]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Δημήτρης', 'last_name' => ' Κρεμαστινός', 'order'=> 4, 'district_id' => 16]);
        $m->groups()->attach([4]);
        $m = App\Member::create(['first_name' => 'Μιχαήλ', 'last_name' => ' Κριτσωτάκης', 'order'=> 5, 'district_id' => 24]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Δημήτριος', 'last_name' => ' Κυριαζίδης', 'order'=> 2, 'district_id' => 15]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Βασίλειος', 'last_name' => ' Κυριακάκης', 'order'=> 3, 'district_id' => 52]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Αγλαϊα', 'last_name' => ' Κυρίτση', 'order'=> 4, 'district_id' => 18]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Πέτρος', 'last_name' => ' Κωνσταντινέας', 'order'=> 2, 'district_id' => 42]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Οδυσσέας', 'last_name' => ' Κωνσταντινόπουλος', 'order'=> 3, 'district_id' => 6]);
        $m->groups()->attach([4]);
        $m = App\Member::create(['first_name' => 'Δημήτριος', 'last_name' => ' Κωνσταντόπουλος', 'order'=> 3, 'district_id' => 4]);
        $m->groups()->attach([4]);
        $m = App\Member::create(['first_name' => 'Ζωή', 'last_name' => ' Κωνσταντοπούλου', 'order'=> 7, 'district_id' => 1]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ηλίας', 'last_name' => ' Κωστοπαναγιώτου', 'order'=> 1, 'district_id' => 54]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Θωμάς', 'last_name' => ' Κώτσιας', 'order'=> 1, 'district_id' => 20]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Λαγός', 'order'=> 4, 'district_id' => 12]);
        $m->groups()->attach([7]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Λαμπρούλης', 'order'=> 5, 'district_id' => 37]);
        $m->groups()->attach([2]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Λαπαβίτσας', 'order'=> 3, 'district_id' => 23]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Σπυρίδωνας', 'last_name' => ' Λάππας', 'order'=> 2, 'district_id' => 28]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Παναγιώτης', 'last_name' => ' Λαφαζάνης', 'order'=> 5, 'district_id' => 12]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Βασιλική', 'last_name' => ' Λέβα', 'order'=> 4, 'district_id' => 52]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ευστάθιος', 'last_name' => ' Λεουτσάκος (Στάθης)', 'order'=> 5, 'district_id' => 3]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ανδρέας', 'last_name' => ' Λοβέρδος', 'order'=> 28, 'district_id' => 10]);
        $m->groups()->attach([4]);
        $m = App\Member::create(['first_name' => 'Σπύρος', 'last_name' => ' Λυκούδης', 'order'=> 8, 'district_id' => 1]);
        $m->groups()->attach([6]);
        $m = App\Member::create(['first_name' => 'Αντιγόνη', 'last_name' => ' Λυμπεράκη', 'order'=> 29, 'district_id' => 10]);
        $m->groups()->attach([6]);
        $m = App\Member::create(['first_name' => 'Γρηγόριος', 'last_name' => ' Μακαρόνας', 'order'=> 6, 'district_id' => 24]);
        $m->groups()->attach([1]);
        $m = App\Member::create(['first_name' => 'Ραχήλ', 'last_name' => ' Μακρή', 'order'=> 4, 'district_id' => 33]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Νικόλαος', 'last_name' => ' Μανιός', 'order'=> 2, 'district_id' => 35]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Χρήστος', 'last_name' => ' Μαντάς', 'order'=> 2, 'district_id' => 26]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Διαμάντω', 'last_name' => ' Μανωλάκου', 'order'=> 6, 'district_id' => 12]);
        $m->groups()->attach([2]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Β. Μαρίνος', 'order'=> 4, 'district_id' => 19]);
        $m->groups()->attach([2]);
        $m = App\Member::create(['first_name' => 'Αικατερίνη', 'last_name' => ' Μάρκου', 'order'=> 7, 'district_id' => 11]);
        $m->groups()->attach([6]);
        $m = App\Member::create(['first_name' => 'Γεωργία', 'last_name' => ' Μαρτίνου', 'order'=> 7, 'district_id' => 8]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Αρτέμιος', 'last_name' => ' Ματθαιόπουλος', 'order'=> 4, 'district_id' => 50]);
        $m->groups()->attach([7]);
        $m = App\Member::create(['first_name' => 'Νικόλαος', 'last_name' => ' Μαυραγάνης', 'order'=> 5, 'district_id' => 19]);
        $m->groups()->attach([1]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Μαυρωτάς', 'order'=> 8, 'district_id' => 8]);
        $m->groups()->attach([6]);
        $m = App\Member::create(['first_name' => 'Αλέξανδρος', 'last_name' => ' Μεϊκόπουλος', 'order'=> 2, 'district_id' => 41]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ευάγγελος-Βασίλειος', 'last_name' => ' Μεϊμαράκης', 'order'=> 30, 'district_id' => 10]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Παναγιώτης', 'last_name' => ' Μηταράκης (Νότης)', 'order'=> 1, 'district_id' => 57]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Τριαντάφυλλος', 'last_name' => ' Μηταφίδης', 'order'=> 11, 'district_id' => 2]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Αλέξιος', 'last_name' => ' Μητρόπουλος', 'order'=> 9, 'district_id' => 8]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Κυριάκος', 'last_name' => ' Μητσοτάκης', 'order'=> 31, 'district_id' => 10]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Ανδρέας', 'last_name' => ' Μιχαηλίδης', 'order'=> 2, 'district_id' => 57]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Νικόλαος', 'last_name' => ' Μιχαλάκης', 'order'=> 3, 'district_id' => 28]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Νικόλαος', 'last_name' => ' Μιχαλολιάκος', 'order'=> 9, 'district_id' => 1]);
        $m->groups()->attach([7]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Μιχελογιαννάκης', 'order'=> 7, 'district_id' => 24]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Νικόλαος', 'last_name' => ' Μίχος', 'order'=> 6, 'district_id' => 19]);
        $m->groups()->attach([7]);
        $m = App\Member::create(['first_name' => 'Μουσταφά', 'last_name' => ' Μουσταφά', 'order'=> 2, 'district_id' => 48]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Θεοδώρα', 'last_name' => ' Μπακογιάννη (Ντόρα)', 'order'=> 10, 'district_id' => 1]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Γεράσιμος', 'last_name' => ' Μπαλαούρας', 'order'=> 3, 'district_id' => 22]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Μπαλάφας', 'order'=> 32, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Συμεών', 'last_name' => ' Μπαλλής', 'order'=> 3, 'district_id' => 41]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Δημήτριος', 'last_name' => ' Μπαξεβανάκης', 'order'=> 4, 'district_id' => 22]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Μπαργιώτας', 'order'=> 6, 'district_id' => 37]);
        $m->groups()->attach([6]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Μπάρκας', 'order'=> 2, 'district_id' => 46]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Μπαρμπαρούσης', 'order'=> 4, 'district_id' => 4]);
        $m->groups()->attach([7]);
        $m = App\Member::create(['first_name' => 'Ευάγγελος', 'last_name' => ' Μπασιάκος', 'order'=> 1, 'district_id' => 13]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Χρήστος', 'last_name' => ' Μπουκώρος', 'order'=> 4, 'district_id' => 41]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Αθανάσιος', 'last_name' => ' Μπούρας', 'order'=> 10, 'district_id' => 8]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Νικόλαος', 'last_name' => ' Μωραΐτης', 'order'=> 5, 'district_id' => 4]);
        $m->groups()->attach([2]);
        $m = App\Member::create(['first_name' => 'Νικόλαος', 'last_name' => ' Νικολόπουλος', 'order'=> 6, 'district_id' => 9]);
        $m->groups()->attach([1]);
        $m = App\Member::create(['first_name' => 'Ανδρέας', 'last_name' => ' Ξανθός', 'order'=> 2, 'district_id' => 47]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Σταυρούλα', 'last_name' => ' Ξουλίδου', 'order'=> 8, 'district_id' => 11]);
        $m->groups()->attach([1]);
        $m = App\Member::create(['first_name' => 'Νικόλαος', 'last_name' => ' Ξυδάκης', 'order'=> 33, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Βασίλειος', 'last_name' => ' Οικονόμου', 'order'=> 5, 'district_id' => 18]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Νίκος', 'last_name' => ' Ορφανός', 'order'=> 7, 'district_id' => 12]);
        $m->groups()->attach([6]);
        $m = App\Member::create(['first_name' => 'Ευγενία', 'last_name' => ' Ουζουνίδου', 'order'=> 5, 'district_id' => 33]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Ουρσουζίδης', 'order'=> 4, 'district_id' => 23]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ηλίας', 'last_name' => ' Παναγιώταρος', 'order'=> 34, 'district_id' => 10]);
        $m->groups()->attach([7]);
        $m = App\Member::create(['first_name' => 'Νικόλαος', 'last_name' => ' Παναγιωτόπουλος', 'order'=> 3, 'district_id' => 27]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Ευστάθιος', 'last_name' => ' Παναγούλης (Στάθης)', 'order'=> 35, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Πάντζας', 'order'=> 11, 'district_id' => 8]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Σάκης', 'last_name' => ' Παπαδόπουλος', 'order'=> 2, 'district_id' => 51]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Αικατερίνη', 'last_name' => ' Παπανάτσιου', 'order'=> 5, 'district_id' => 41]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Αλεξάνδρα', 'last_name' => ' Παπαρήγα', 'order'=> 6, 'district_id' => 18]);
        $m->groups()->attach([2]);
        $m = App\Member::create(['first_name' => 'Αθανάσιος', 'last_name' => ' Παπαχριστόπουλος', 'order'=> 36, 'district_id' => 10]);
        $m->groups()->attach([1]);
        $m = App\Member::create(['first_name' => 'Νικός', 'last_name' => ' Σ. Παππάς', 'order'=> 37, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Χρήστος', 'last_name' => ' Παππάς', 'order'=> 7, 'district_id' => 18]);
        $m->groups()->attach([7]);
        $m = App\Member::create(['first_name' => 'Θεόδωρος', 'last_name' => ' Παραστατίδης', 'order'=> 2, 'district_id' => 32]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Αθανάσιος', 'last_name' => ' Παφίλης', 'order'=> 38, 'district_id' => 10]);
        $m->groups()->attach([2]);
        $m = App\Member::create(['first_name' => 'Αθανάσιος', 'last_name' => ' Πετράκος', 'order'=> 3, 'district_id' => 42]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Πλακιωτάκης', 'order'=> 2, 'district_id' => 38]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Παύλος', 'last_name' => ' Πολάκης', 'order'=> 3, 'district_id' => 56]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ελένη', 'last_name' => ' Ράπτη', 'order'=> 12, 'district_id' => 2]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Δημήτριος', 'last_name' => ' Ρίζος', 'order'=> 4, 'district_id' => 17]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Γαβριήλ', 'last_name' => ' Σακελλαρίδης', 'order'=> 11, 'district_id' => 1]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Μάριος', 'last_name' => ' Σαλμάς', 'order'=> 6, 'district_id' => 4]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Αντώνιος', 'last_name' => ' Σαμαράς', 'order'=> 4, 'district_id' => 42]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Στέφανος', 'last_name' => ' Σαμοΐλης', 'order'=> 3, 'district_id' => 30]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Νεκτάριος', 'last_name' => ' Σαντορινιός', 'order'=> 5, 'district_id' => 16]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Δέσποινα', 'last_name' => ' Σβερώνη-Χονδρονάσιου', 'order'=> 7, 'district_id' => 37]);
        $m->groups()->attach([7]);
        $m = App\Member::create(['first_name' => 'Δημήτριος', 'last_name' => ' Σεβαστάκης', 'order'=> 1, 'district_id' => 49]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Σέλτσας', 'order'=> 2, 'district_id' => 53]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Σηφάκης', 'order'=> 2, 'district_id' => 44]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Χρήστος', 'last_name' => ' Σιμορέλης', 'order'=> 3, 'district_id' => 51]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Σκανδαλίδης', 'order'=> 12, 'district_id' => 1]);
        $m->groups()->attach([4]);
        $m = App\Member::create(['first_name' => 'Αθανάσιος', 'last_name' => ' Σκούμας', 'order'=> 2, 'district_id' => 13]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Παναγιώτης', 'last_name' => ' Σκουρλέτης (Πάνος)(en)', 'order'=> 8, 'district_id' => 18]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Παναγιώτης', 'last_name' => ' Σκουρολιάκος (Πάνος)', 'order'=> 12, 'district_id' => 8]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ελισσάβετ', 'last_name' => ' Σκούφα (Μπέττυ)', 'order'=> 3, 'district_id' => 45]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Σκρέκας', 'order'=> 4, 'district_id' => 51]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Χρήστος', 'last_name' => ' Σμίας', 'order'=> 3, 'district_id' => 44]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Σταθάκης', 'order'=> 4, 'district_id' => 56]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Σταθάς', 'order'=> 3, 'district_id' => 13]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Χρήστος', 'last_name' => ' Σταϊκούρας', 'order'=> 5, 'district_id' => 52]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Ελένη', 'last_name' => ' Σταματάκη', 'order'=> 6, 'district_id' => 3]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Δημήτριος', 'last_name' => ' Ι. Σταμάτης', 'order'=> 9, 'district_id' => 18]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Αφροδίτη', 'last_name' => ' Σταμπουλή', 'order'=> 5, 'district_id' => 50]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Στέφος', 'order'=> 3, 'district_id' => 26]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Δημήτριος', 'last_name' => ' Στρατούλης', 'order'=> 39, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ευριπίδης', 'last_name' => ' Στυλιανίδης', 'order'=> 3, 'district_id' => 48]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Στύλιος', 'order'=> 2, 'district_id' => 7]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Εμμανουήλ', 'last_name' => ' Συντυχάκης', 'order'=> 8, 'district_id' => 24]);
        $m->groups()->attach([2]);
        $m = App\Member::create(['first_name' => 'Αντώνιος', 'last_name' => ' Συρίγος', 'order'=> 3, 'district_id' => 35]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Νικόλαος', 'last_name' => ' Συρμαλένιος', 'order'=> 4, 'district_id' => 35]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ελένη', 'last_name' => ' Σωτηρίου', 'order'=> 13, 'district_id' => 8]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Τασούλας', 'order'=> 4, 'district_id' => 26]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Σταύρος', 'last_name' => ' Τάσσος', 'order'=> 3, 'district_id' => 39]);
        $m->groups()->attach([2]);
        $m = App\Member::create(['first_name' => 'Χριστίνα', 'last_name' => ' Ταχιάου', 'order'=> 13, 'district_id' => 2]);
        $m->groups()->attach([6]);
        $m = App\Member::create(['first_name' => 'Κυριακή', 'last_name' => ' Τεκτονίδου (Βούλα)', 'order'=> 14, 'district_id' => 2]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Τζαβάρας', 'order'=> 5, 'district_id' => 22]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Θεοδώρα', 'last_name' => ' Τζάκρη', 'order'=> 4, 'district_id' => 44]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Χαρίλαος', 'last_name' => ' Τζαμακλής', 'order'=> 4, 'district_id' => 45]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Δανάη', 'last_name' => ' Τζήκα-Κωστοπούλου', 'order'=> 6, 'district_id' => 41]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Μερόπη', 'last_name' => ' Τζούφη', 'order'=> 5, 'district_id' => 26]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Νικόλαος', 'last_name' => ' Τόσκας', 'order'=> 10, 'district_id' => 18]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ιωάννης', 'last_name' => ' Τραγάκης', 'order'=> 8, 'district_id' => 12]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Αλέκος', 'last_name' => ' Τριανταφυλλίδης', 'order'=> 15, 'district_id' => 2]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Μαρία', 'last_name' => ' Τριανταφύλλου', 'order'=> 7, 'district_id' => 4]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Ευκλείδης', 'last_name' => ' Τσακαλώτος', 'order'=> 40, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Αλεξάνδρα', 'last_name' => ' Τσανάκα', 'order'=> 4, 'district_id' => 27]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Τσιάρας', 'order'=> 4, 'district_id' => 28]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Αλέξιος', 'last_name' => ' Τσίπρας', 'order'=> 13, 'district_id' => 1]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Βασίλειος', 'last_name' => ' Τσίρκας', 'order'=> 3, 'district_id' => 7]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Τσουκαλάς', 'order'=> 11, 'district_id' => 18]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Σωκράτης', 'last_name' => ' Φάμελλος', 'order'=> 9, 'district_id' => 11]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Νικόλαος', 'last_name' => ' Φίλης', 'order'=> 14, 'district_id' => 1]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Θεόδωρος', 'last_name' => ' Φορτσάκης', 'order'=> 12, 'district_id' => 18]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Ιάσων', 'last_name' => ' Φωτήλας', 'order'=> 7, 'district_id' => 9]);
        $m->groups()->attach([6]);
        $m = App\Member::create(['first_name' => 'Θεανώ', 'last_name' => ' Φωτίου', 'order'=> 41, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Παύλος', 'last_name' => ' Χαϊκάλης', 'order'=> 14, 'district_id' => 8]);
        $m->groups()->attach([1]);
        $m = App\Member::create(['first_name' => 'Κυριάκος', 'last_name' => ' Χαρακίδης', 'order'=> 3, 'district_id' => 15]);
        $m->groups()->attach([6]);
        $m = App\Member::create(['first_name' => 'Μάξιμος', 'last_name' => ' Χαρακόπουλος', 'order'=> 8, 'district_id' => 37]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Δέσποινα', 'last_name' => ' Χαραλαμπίδου', 'order'=> 16, 'district_id' => 2]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Κωνσταντίνος', 'last_name' => ' Χατζηδάκης (Κωστής)', 'order'=> 42, 'district_id' => 10]);
        $m->groups()->attach([3]);
        $m = App\Member::create(['first_name' => 'Αλέξανδρος', 'last_name' => ' Χατζηδημητρίου', 'order'=> 6, 'district_id' => 50]);
        $m->groups()->attach([6]);
        $m = App\Member::create(['first_name' => 'Βασίλειος', 'last_name' => ' Χατζηλάμπρου', 'order'=> 8, 'district_id' => 9]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Χρήστος', 'last_name' => ' Χατζησάββας', 'order'=> 3, 'district_id' => 32]);
        $m->groups()->attach([7]);
        $m = App\Member::create(['first_name' => 'Νικόλαος', 'last_name' => ' Χουντής', 'order'=> 43, 'district_id' => 10]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Παρασκευή', 'last_name' => ' Χριστοφιλοπούλου (Εύη)', 'order'=> 15, 'district_id' => 8]);
        $m->groups()->attach([4]);
        $m = App\Member::create(['first_name' => 'Γρηγόριος', 'last_name' => ' Ψαριανός', 'order'=> 44, 'district_id' => 10]);
        $m->groups()->attach([6]);
        $m = App\Member::create(['first_name' => 'Ελένη', 'last_name' => ' Ψαρρέα', 'order'=> 5, 'district_id' => 42]);
        $m->groups()->attach([5]);
        $m = App\Member::create(['first_name' => 'Γεώργιος', 'last_name' => ' Ψυχογιός', 'order'=> 4, 'district_id' => 34]);
        $m->groups()->attach([5]);
    }
}